---
extends: default
rules:
  line-length:
    max: 88
  braces:
    max-spaces-inside: -1
  truthy:
    check-keys: false # allow GitHub Actions `on:` key
  comments:
    min-spaces-from-content: 1 # project uses single-space inline comments
  document-start: disable
