# .github/workflows/ci.yml:
# Configures the CI workflow to run tests and upload coverage reports.
---
name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4.2.2

      - name: setup-python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'

      - name: cache-pip-and-poetry
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: install-poetry
        run: pip install poetry

      - name: install-dependencies
        run: poetry install --no-interaction --no-ansi --with test

      - name: run-tests
        run: make test

      - name: upload-coverage
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
