---
name: release

on:
  workflow_run:
    workflows: ['ci']
    types: [completed]
    branches: [main]

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout-code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: install-poetry
        run: pipx install 'poetry>=2.3,<3'

      - name: setup-python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.14'
          cache: poetry

      - name: setup-node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20.x'
          cache: npm

      - name: install-node-dependencies
        run: npm ci

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: make release
